---
name: Get data lake folder size
on:
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    get-size:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: install pwsh modules
              shell: pwsh
              run: |
                    Install-Module -Name Az.Accounts -Repository PSGallery -Force -AllowClobber -Scope CurrentUser
                    Install-Module -Name Az.Storage -Repository PSGallery -Force -AllowClobber -Scope CurrentUser

            - name: Login to Azure
              shell: pwsh
              run: |
                $ClientSecret = "${{ secrets.CLIENTSECRET }}"
                $SecurePassword = ConvertTo-SecureString -String $ClientSecret -AsPlainText -Force
                $TenantId = "${{ secrets.TENANTID }}"
                $ApplicationId = "${{ secrets.APPLICATIONID }}"
                $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $ApplicationId, $SecurePassword
                az login --service-principal -u $ApplicationId -p $ClientSecret --tenant $TenantId
                az login --service-principal -u $ApplicationId -p $ClientSecret --tenant $TenantId
                Connect-AzAccount -ServicePrincipal -TenantId $TenantId -Credential $Credential
                

            - name: Get size of data lake folder
              uses: azure/powershell@v2
              with:
                inlineScript: './scripts/dls-folder-size.ps1'
                azPSVersion: 'Latest'

            - name: upload generated file
              uses: actions/upload-artifact@v4
              with:
                name: datalake-size
                path: ./output/
            - name: list the generated file
              shell: pwsh
              run: |
                ls -lh ./output/       