---
name: Get data lake folder size
on:
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    get-size:
        runs-on: ubuntu-latest
        env: 
            dls_account_name: "backendterraformstate1"

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: install pwsh modules
              shell: pwsh
              run: |
                    Install-Module -Name Az.Accounts -Repository PSGallery -Force -AllowClobber -Scope CurrentUser
                    Install-Module -Name Az.Storage -Repository PSGallery -Force -AllowClobber -Scope CurrentUser

            - name: print current directoy
              shell: pwsh
              run: |
                $currentDirectory = Get-Location
                write-host "Current directory: $currentDirectory"
              
            - name: Login to Azure
              shell: pwsh
              run: |
                $ClientSecret = "${{ secrets.CLIENTSECRET }}"
                $SecurePassword = ConvertTo-SecureString -String $ClientSecret -AsPlainText -Force
                $TenantId = "${{ secrets.TENANTID }}"
                $ApplicationId = "${{ secrets.APPLICATIONID }}"
                $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $ApplicationId, $SecurePassword
                az login --service-principal -u $ApplicationId -p $ClientSecret --tenant $TenantId
                az login --service-principal -u $ApplicationId -p $ClientSecret --tenant $TenantId
                Connect-AzAccount -ServicePrincipal -TenantId $TenantId -Credential $Credential
                
            - name: Get size of data lake folder
              uses: azure/powershell@v2
              with:
                inlineScript: |
                    $dls_account_name = "${{ env.dls_account_name }}"
                    ./scripts/dls-folder-size.ps1 -dlsstorageAccountName $dls_account_name
                azPSVersion: 'Latest'

            - name: list the files in the current directory
              shell: bash
              run: |
                echo "Listing files in the current directory:"
                currentDirectory=$(pwd)
                echo "current working directory is $currentDirectory"
                ls -ltrh   
                dls_account_name = "${dls_account_name}"
                az storage fs file upload --source $currentDirectory/${dls_account_name}.*.csv --path storagesizefiles/datalake-size.csv --account-name backendterraformstate1 --file-system cantaioner-rz --auth-mode login --overwrite true
